import type { SkillSpec, GeneratedFile } from "../types";

export function generateClaude(spec: SkillSpec): GeneratedFile[] {
  const lines: string[] = [];

  lines.push(`# ${spec.name}`);
  if (spec.display_name) lines.push(`\n**${spec.display_name}**`);
  lines.push(`\n${spec.description}`);

  lines.push(`\n## Metadata\n`);
  lines.push(`- **Version:** ${spec.version}`);
  lines.push(`- **Complexity:** ${spec.complexity || "moderate"}`);
  lines.push(`- **Author:** ${spec.author || "Unknown"}`);
  lines.push(`- **Frameworks:** ${(spec.target_frameworks || []).join(", ")}`);

  if (spec.problem_statement) {
    lines.push(`\n## Problem Statement\n\n${spec.problem_statement}`);
  }

  if (spec.target_user) {
    lines.push(`\n## Target User\n\n${spec.target_user}`);
  }

  if (spec.trigger_patterns?.length) {
    lines.push(`\n## Trigger Patterns\n\nWhen to activate this skill:\n`);
    for (const p of spec.trigger_patterns) lines.push(`- ${p}`);
  }

  lines.push(`\n## Capabilities\n`);
  for (const cap of spec.capabilities) {
    lines.push(`### ${cap.name}\n\n${cap.description}\n`);
    if (cap.parameters?.length) {
      lines.push(`**Parameters:**`);
      for (const p of cap.parameters) {
        lines.push(`- \`${p.name}\` (${p.type}${p.required ? ", required" : ""}): ${p.description}`);
      }
      lines.push("");
    }
  }

  if (spec.examples?.length) {
    lines.push(`## Examples\n`);
    for (let i = 0; i < spec.examples.length; i++) {
      const ex = spec.examples[i];
      lines.push(`### Example ${i + 1}${ex.name ? `: ${ex.name}` : ""}\n`);
      if (ex.input) lines.push(`**Input:**\n\`\`\`\n${typeof ex.input === "string" ? ex.input : JSON.stringify(ex.input, null, 2)}\n\`\`\`\n`);
      if (ex.expected_output) lines.push(`**Expected Output:**\n\`\`\`\n${typeof ex.expected_output === "string" ? ex.expected_output : JSON.stringify(ex.expected_output, null, 2)}\n\`\`\`\n`);
      if (ex.notes) lines.push(`*${ex.notes}*\n`);
    }
  }

  if (spec.edge_cases?.length) {
    lines.push(`## Edge Cases\n`);
    for (const e of spec.edge_cases) lines.push(`- ${e}`);
    lines.push("");
  }

  if (spec.error_handling?.length) {
    lines.push(`## Error Handling\n`);
    for (const err of spec.error_handling) lines.push(`- **${err.condition}**: ${err.handling}`);
    lines.push("");
  }

  if (spec.safety_boundaries?.length) {
    lines.push(`## Safety Boundaries\n\nThis skill must NEVER:\n`);
    for (const b of spec.safety_boundaries) lines.push(`- ${b}`);
    lines.push("");
  }

  if (spec.dependencies?.length) {
    lines.push(`## Dependencies\n`);
    for (const d of spec.dependencies) lines.push(`- ${d}`);
    lines.push("");
  }

  lines.push(`---\n*Generated by Skill Forge*`);

  return [{ filename: "SKILL.md", content: lines.join("\n"), framework: "claude", type: "skill_definition" }];
}
