import type { SkillSpec, GeneratedFile } from "../types";

const typeMap: Record<string, string> = {
  string: "str", number: "float", boolean: "bool", array: "list", object: "dict",
};

export function generateCrewai(spec: SkillSpec): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const displayName = spec.name.replace(/-/g, " ").replace(/\b\w/g, c => c.toUpperCase());

  // agent_config.yaml
  const configLines = [
    `# ${spec.name} — CrewAI Agent Configuration`,
    `# Generated by Skill Forge`,
    ``,
    `agent:`,
    `  role: "${displayName}"`,
    `  goal: "${spec.description}"`,
    `  backstory: >`,
    `    You are a specialized agent that ${spec.description.toLowerCase()}.`,
  ];
  if (spec.problem_statement) {
    configLines.push(`    You solve the following problem: ${spec.problem_statement}`);
  }
  configLines.push(`  verbose: true`);
  configLines.push(`  allow_delegation: false`);
  configLines.push(`  tools:`);
  for (const cap of spec.capabilities) {
    configLines.push(`    - ${cap.name.replace(/-/g, "_")}`);
  }

  files.push({ filename: "agent_config.yaml", content: configLines.join("\n"), framework: "crewai", type: "config" });

  // tools.py
  const toolsLines = [
    `"""${spec.name} — CrewAI Tools`,
    ``,
    `${spec.description}`,
    ``,
    `Generated by Skill Forge`,
    `"""`,
    ``,
    `from crewai.tools import tool`,
  ];

  for (const cap of spec.capabilities) {
    const fnName = cap.name.replace(/-/g, "_");
    const params = (cap.parameters || [])
      .map(p => `${p.name}: ${typeMap[p.type] || "str"}`)
      .join(", ");
    toolsLines.push(``);
    toolsLines.push(``);
    toolsLines.push(`@tool("${cap.name}")`);
    toolsLines.push(`def ${fnName}(${params}) -> str:`);
    toolsLines.push(`    """${cap.description}"""`);
    toolsLines.push(`    # TODO: Implement ${cap.name}`);
    toolsLines.push(`    raise NotImplementedError("${cap.name} not yet implemented")`);
  }

  files.push({ filename: "tools.py", content: toolsLines.join("\n"), framework: "crewai", type: "tools" });

  return files;
}
