import type { SkillSpec, GeneratedFile } from "../types";

const typeMap: Record<string, string> = {
  string: "str", number: "float", boolean: "bool", array: "list", object: "dict",
};

export function generateMcp(spec: SkillSpec): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const pyName = spec.name.replace(/-/g, "_");

  // server.py
  const serverLines: string[] = [
    `"""${spec.name} — MCP Server`,
    ``,
    `${spec.description}`,
    ``,
    `Generated by Skill Forge`,
    `"""`,
    ``,
    `from mcp.server.fastmcp import FastMCP`,
    ``,
    `mcp = FastMCP("${spec.name}")`,
  ];

  for (const cap of spec.capabilities) {
    const fnName = cap.name.replace(/-/g, "_");
    const params = (cap.parameters || [])
      .map(p => {
        const pyType = typeMap[p.type] || "str";
        return p.required ? `${p.name}: ${pyType}` : `${p.name}: ${pyType} = None`;
      })
      .join(", ");

    serverLines.push(``);
    serverLines.push(``);
    serverLines.push(`@mcp.tool()`);
    serverLines.push(`def ${fnName}(${params}) -> str:`);
    serverLines.push(`    """${cap.description}`);
    if (cap.parameters?.length) {
      serverLines.push(``);
      serverLines.push(`    Args:`);
      for (const p of cap.parameters) {
        serverLines.push(`        ${p.name}: ${p.description}`);
      }
    }
    serverLines.push(`    Returns:`);
    serverLines.push(`        Result of ${cap.name}`);
    serverLines.push(`    """`);
    serverLines.push(`    # TODO: Implement ${cap.name}`);
    serverLines.push(`    raise NotImplementedError("${cap.name} not yet implemented")`);
  }

  serverLines.push(``);
  serverLines.push(``);
  serverLines.push(`if __name__ == "__main__":`);
  serverLines.push(`    mcp.run()`);

  files.push({ filename: "server.py", content: serverLines.join("\n"), framework: "mcp", type: "server" });

  // requirements.txt
  const reqLines = [`# Requirements for ${spec.name} MCP server`, `fastmcp>=2.0.0`];
  if (spec.dependencies?.length) {
    for (const dep of spec.dependencies) reqLines.push(dep);
  }
  files.push({ filename: "requirements.txt", content: reqLines.join("\n"), framework: "mcp", type: "requirements" });

  // README.md
  const readmeLines = [
    `# ${spec.name} — MCP Server`, ``, `${spec.description}`, ``,
    `## Setup`, ``, "```bash", `pip install -r requirements.txt`, "```", ``,
    `## Usage`, ``, "```bash", `python server.py`, "```", ``,
    `## Tools`, ``,
  ];
  for (const cap of spec.capabilities) {
    readmeLines.push(`### ${cap.name}`, `${cap.description}`, ``);
  }
  readmeLines.push(`---`, `*Generated by Skill Forge*`);
  files.push({ filename: "README.md", content: readmeLines.join("\n"), framework: "mcp", type: "readme" });

  return files;
}
